import { Customer, Driver, Merchant, PartnershipArea, ActivityLog } from './types';

export const INITIAL_AREAS: PartnershipArea[] = [
  {
    id: 'surabaya',
    type: 'Kota',
    name: 'Kota Surabaya',
    regionalPartnerName: 'Hendra Wijaya',
    phone: '081122334455',
    commissionRate: 3.0,
    status: 'Active',
    serviceFeeMultiplier: 1.0,
    totalRevenue: 24500000,
  },
  {
    id: 'sidoarjo',
    type: 'Kabupaten',
    name: 'Kabupaten Sidoarjo',
    regionalPartnerName: 'Ahmad Yani',
    phone: '081233445566',
    commissionRate: 2.5,
    status: 'Active',
    serviceFeeMultiplier: 0.95,
    totalRevenue: 18200000,
  },
  {
    id: 'gresik',
    type: 'Kabupaten',
    name: 'Kabupaten Gresik',
    regionalPartnerName: 'Lilis Suryani',
    phone: '081344556677',
    commissionRate: 2.5,
    status: 'Active',
    serviceFeeMultiplier: 0.95,
    totalRevenue: 9800000,
  },
  {
    id: 'malang',
    type: 'Kota',
    name: 'Kota Malang',
    regionalPartnerName: 'Dimas Prabowo',
    phone: '081455667788',
    commissionRate: 3.0,
    status: 'Active',
    serviceFeeMultiplier: 1.0,
    totalRevenue: 12400000,
  },
  {
    id: 'jakarta',
    type: 'Kota',
    name: 'DKI Jakarta',
    regionalPartnerName: 'Bambang Hermawan',
    phone: '081566778899',
    commissionRate: 4.0,
    status: 'Active',
    serviceFeeMultiplier: 1.2,
    totalRevenue: 54100000,
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'C-001',
    username: 'budis',
    name: 'Budi Santoso',
    phone: '081234567890',
    email: 'budi.santoso@gmail.com',
    wallet_balance: 150000,
    status: 'Active',
    createdAt: '2026-06-01',
    registeredAreaId: 'surabaya',
  },
  {
    id: 'C-002',
    username: 'sitia',
    name: 'Siti Aminah',
    phone: '081398765432',
    email: 'siti.aminah@yahoo.com',
    wallet_balance: 245000,
    status: 'Active',
    createdAt: '2026-06-10',
    registeredAreaId: 'sidoarjo',
  },
  {
    id: 'C-003',
    username: 'jokow',
    name: 'Joko Waluyo',
    phone: '085711223344',
    email: 'joko.waluyo@outlook.com',
    wallet_balance: 12000,
    status: 'Active',
    createdAt: '2026-06-15',
    registeredAreaId: 'gresik',
  },
  {
    id: 'C-004',
    username: 'dewis',
    name: 'Dewi Sastrawati',
    phone: '082155443322',
    email: 'dewi.s@gmail.com',
    wallet_balance: 750000,
    status: 'Active',
    createdAt: '2026-06-25',
    registeredAreaId: 'surabaya',
  },
  {
    id: 'C-005',
    username: 'rizky_p',
    name: 'Rizky Pratama',
    phone: '089988776655',
    email: 'rizky.pratama@gmail.com',
    wallet_balance: 0,
    status: 'Pending',
    createdAt: '2026-06-29',
    registeredAreaId: 'malang',
  },
  {
    id: 'C-006',
    username: 'ani_m',
    name: 'Ani Maryuni',
    phone: '081244332211',
    email: 'ani.m@gmail.com',
    wallet_balance: 85000,
    status: 'Active',
    createdAt: '2026-06-29',
    registeredAreaId: 'jakarta',
  },
  {
    id: 'C-007',
    username: 'eko_w',
    name: 'Eko Wahyudi',
    phone: '085388779922',
    email: 'eko.wahyudi@gmail.com',
    wallet_balance: 320000,
    status: 'Suspended',
    createdAt: '2026-05-14',
    registeredAreaId: 'sidoarjo',
  }
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'D-001',
    username: 'supri_motor',
    name: 'Supriadi',
    phone: '081211112222',
    email: 'supriadi.ojol@gmail.com',
    wallet_balance: 45000,
    vehicleType: 'Motor',
    vehiclePlate: 'L 1234 AB',
    rating: 4.9,
    status: 'Active',
    registeredAreaId: 'surabaya',
    createdAt: '2026-05-10',
  },
  {
    id: 'D-002',
    username: 'mulyono_car',
    name: 'Mulyono Santoso',
    phone: '081322223333',
    email: 'mulyono.mobil@gmail.com',
    wallet_balance: 890000,
    vehicleType: 'Mobil',
    vehiclePlate: 'W 5678 CD',
    rating: 4.8,
    status: 'Active',
    registeredAreaId: 'sidoarjo',
    createdAt: '2026-05-20',
  },
  {
    id: 'D-003',
    username: 'agus_kurir',
    name: 'Agus Setiawan',
    phone: '085733334444',
    email: 'agus.setiawan@gmail.com',
    wallet_balance: 15000,
    vehicleType: 'Kurir',
    vehiclePlate: 'B 9999 XYZ',
    rating: 4.2,
    status: 'Active',
    registeredAreaId: 'jakarta',
    createdAt: '2026-06-05',
  },
  {
    id: 'D-004',
    username: 'rony_bentor',
    name: 'Rony Hermawan',
    phone: '082144445555',
    email: 'rony.bentor@gmail.com',
    wallet_balance: 0,
    vehicleType: 'Bentor',
    vehiclePlate: 'N 4321 DE',
    rating: 0,
    status: 'Pending',
    registeredAreaId: 'malang',
    createdAt: '2026-06-28',
  },
  {
    id: 'D-005',
    username: 'tati_driver',
    name: 'Tati Mulyati',
    phone: '081922339900',
    email: 'tati.mulyati@gmail.com',
    wallet_balance: 125000,
    vehicleType: 'Motor',
    vehiclePlate: 'F 4512 JK',
    rating: 4.7,
    status: 'Active',
    registeredAreaId: 'jakarta',
    createdAt: '2026-06-18',
  },
  {
    id: 'D-006',
    username: 'hendra_car',
    name: 'Hendra Saputra',
    phone: '087855660011',
    email: 'hendra.saputra@gmail.com',
    wallet_balance: 50000,
    vehicleType: 'Mobil',
    vehiclePlate: 'W 9821 OP',
    rating: 3.5,
    status: 'Suspended',
    registeredAreaId: 'sidoarjo',
    createdAt: '2026-06-01',
  }
];

export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'M-001',
    username: 'bakso_pakde',
    name: 'Sugeng Riyadi',
    businessName: 'Bakso Pakde Kumis',
    phone: '081277778888',
    email: 'pakdekumis@gmail.com',
    wallet_balance: 1250000,
    category: 'Food',
    commissionRate: 15,
    status: 'Active',
    registeredAreaId: 'surabaya',
    createdAt: '2026-04-12',
  },
  {
    id: 'M-002',
    username: 'indo_mart_sda',
    name: 'Robert Hartono',
    businessName: 'IndoMart Sidoarjo Square',
    phone: '081388889999',
    email: 'indomart.sda@gmail.com',
    wallet_balance: 3400000,
    category: 'Mart',
    commissionRate: 10,
    status: 'Active',
    registeredAreaId: 'sidoarjo',
    createdAt: '2026-05-01',
  },
  {
    id: 'M-003',
    username: 'apotek_sehat',
    name: 'Dr. Farida Amanda',
    businessName: 'Apotek Sehat Sentosa',
    phone: '085799990000',
    email: 'sehat.sentosa@gmail.com',
    wallet_balance: 0,
    category: 'Pharmacy',
    commissionRate: 12,
    status: 'Pending',
    registeredAreaId: 'gresik',
    createdAt: '2026-06-29',
  },
  {
    id: 'M-004',
    username: 'kopi_malang',
    name: 'Gilang Ramadhan',
    businessName: 'Kopi Kenangan Malang',
    phone: '081900112233',
    email: 'kopikenangan.mlg@gmail.com',
    wallet_balance: 750000,
    category: 'Food',
    commissionRate: 15,
    status: 'Active',
    registeredAreaId: 'malang',
    createdAt: '2026-06-15',
  },
  {
    id: 'M-005',
    username: 'mart_express_jkt',
    name: 'William Wijaya',
    businessName: 'Radjago Express Jakarta Pusat',
    phone: '081288990011',
    email: 'express.jkt@radjago.id',
    wallet_balance: 12000000,
    category: 'Express',
    commissionRate: 8,
    status: 'Active',
    registeredAreaId: 'jakarta',
    createdAt: '2026-03-20',
  }
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: 'L-101',
    category: 'Customer',
    type: 'Create',
    description: 'Pendaftaran baru pelanggan Rizky Pratama dari wilayah Kota Malang',
    timestamp: '2026-06-29 14:32',
    user: 'Sistem',
  },
  {
    id: 'L-102',
    category: 'Driver',
    type: 'Create',
    description: 'Driver Rony Hermawan mendaftar dengan armada Bentor di Kota Malang',
    timestamp: '2026-06-28 11:15',
    user: 'Sistem',
  },
  {
    id: 'L-103',
    category: 'Merchant',
    type: 'Verify',
    description: 'Persetujuan pendaftaran mitra kuliner Bakso Pakde Kumis di Kota Surabaya',
    timestamp: '2026-06-27 09:00',
    user: 'Admin Utama',
  },
  {
    id: 'L-104',
    category: 'Partnership',
    type: 'Update',
    description: 'Penyesuaian bagi hasil kemitraan wilayah DKI Jakarta menjadi 4.0%',
    timestamp: '2026-06-26 16:45',
    user: 'Admin Keuangan',
  },
  {
    id: 'L-105',
    category: 'Customer',
    type: 'Transaction',
    description: 'Manual Top Up Saldo Dompet Budi Santoso Rp 100,000',
    timestamp: '2026-06-26 15:10',
    user: 'Admin Utama',
  }
];
